version: '2'

services:

    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        restart: unless-stopped
        environment:
            - DEFAULT_HOST=site.lennon.cloud
            - LETSENCRYPT_HOST=site.lennon.cloud
            - LETSENCRYPT_EMAIL=lennonalvesdias@gmail.com
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
        ports:
            - "80:80"
            - "443:443"
        networks:
            - "proxy-tier"

    proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        restart: unless-stopped
        environment:
            - NGINX_PROXY_CONTAINER=proxy
        volumes_from:
            - "proxy"
        depends_on:
            - "proxy"
        networks:
            - "proxy-tier"

volumes:
    certs:
    vhost.d:
    html:

networks:
    proxy-tier:
        external: true

