name: Build & Deploy

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - develop
      - hotfix/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build nodejs (app)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Build & Push
        uses: docker/build-push-action@v1.1.0
        with:
          username: lennonalvesdias
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: lennonalvesdias/lennonalvesdias.github.io/site
          registry: docker.pkg.github.com
          tags: ${{ github.sha }}, latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            cat ./github_token.txt | docker login docker.pkg.github.com -u lennonalvesdias --password-stdin
            docker rm -f site || true
            docker run -d --name site -p 1994:80 --restart=always --net nginx-proxy -e VIRTUAL_HOST=site.lennon.cloud,lennon.cloud -e LETSENCRYPT_HOST=site.lennon.cloud,lennon.cloud -e LETSENCRYPT_EMAIL=lennonalvesdias@gmail.com docker.pkg.github.com/lennonalvesdias/lennonalvesdias.github.io/site
