name: Build & Deploy

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - develop
      - hotfix/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build nodejs (app)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          login-server: registry.lennon.cloud
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Build
        run: |
          docker build . -t registry.lennon.cloud/lennon/site:${{ github.sha }}
          docker tag registry.lennon.cloud/lennon/site:${{ github.sha }} registry.lennon.cloud/lennon/site:latest
          docker push registry.lennon.cloud/lennon/site:${{ github.sha }}
          docker push registry.lennon.cloud/lennon/site:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            docker rm -f site || true
            docker run -d --name site -p 1994:80 --restart=always --net nginx-proxy -e VIRTUAL_HOST=site.lennon.cloud -e LETSENCRYPT_HOST=site.lennon.cloud -e LETSENCRYPT_EMAIL=lennonalvesdias@gmail.com registry.lennon.cloud/lennon/site
